export interface TeacherSeed {
  name: string;
  subjects: string[];
}

// 60 unique teachers, each with 2-4 subject affinities so no single
// instructor is overloaded and subjects have realistic instructor variety.
export const TEACHERS: TeacherSeed[] = [
  { name: "Rahul Mehta", subjects: ["Computer Science", "Programming", "Python"] },
  { name: "Sneha Kulkarni", subjects: ["Mathematics", "Algebra", "Geometry"] },
  { name: "Aditya Rao", subjects: ["Physics", "Science"] },
  { name: "Priya Nair", subjects: ["Biology", "Science", "Environmental Science"] },
  { name: "Vikram Singh", subjects: ["Chemistry", "Science"] },
  { name: "Ananya Iyer", subjects: ["English", "Literature", "Grammar"] },
  { name: "Karan Malhotra", subjects: ["History", "Geography"] },
  { name: "Divya Menon", subjects: ["Art", "Drawing"] },
  { name: "Rohan Kapoor", subjects: ["Robotics", "Artificial Intelligence", "Programming"] },
  { name: "Ishaan Verma", subjects: ["Web Development", "Coding", "Computer Science"] },
  { name: "Meera Pillai", subjects: ["Music"] },
  { name: "Arjun Desai", subjects: ["Public Speaking", "English"] },
  { name: "Kavya Reddy", subjects: ["Economics"] },
  { name: "Nikhil Joshi", subjects: ["Mathematics", "Logical Reasoning", "Competitive Exams"] },
  { name: "Tanvi Shah", subjects: ["French"] },
  { name: "Aarav Bhatt", subjects: ["Spanish"] },
  { name: "Riya Chatterjee", subjects: ["Geometry", "Algebra", "Mathematics"] },
  { name: "Siddharth Agarwal", subjects: ["Physics", "Mathematics"] },
  { name: "Neha Trivedi", subjects: ["Chemistry", "Biology"] },
  { name: "Aryan Choudhary", subjects: ["Python", "Programming", "Artificial Intelligence"] },
  { name: "Pooja Bansal", subjects: ["English", "Grammar", "Public Speaking"] },
  { name: "Devansh Saxena", subjects: ["Robotics", "Computer Science"] },
  { name: "Simran Kaur", subjects: ["Art", "Drawing", "Music"] },
  { name: "Yash Thakur", subjects: ["History", "Geography", "Economics"] },
  { name: "Anjali Deshmukh", subjects: ["Science", "Environmental Science", "Biology"] },
  { name: "Manish Pandey", subjects: ["Web Development", "Coding"] },
  { name: "Ritika Sharma", subjects: ["Literature", "English"] },
  { name: "Kabir Khanna", subjects: ["Competitive Exams", "Logical Reasoning"] },
  { name: "Sanya Kapadia", subjects: ["Mathematics", "Algebra"] },
  { name: "Dhruv Bhalla", subjects: ["Physics", "Chemistry"] },
  { name: "Ira Sengupta", subjects: ["Biology", "Chemistry"] },
  { name: "Vivaan Chawla", subjects: ["Artificial Intelligence", "Python", "Computer Science"] },
  { name: "Aisha Siddiqui", subjects: ["French", "English"] },
  { name: "Rajat Mathur", subjects: ["Spanish", "Geography"] },
  { name: "Nandini Rane", subjects: ["Music", "Art"] },
  { name: "Harsh Vardhan", subjects: ["Geometry", "Mathematics", "Logical Reasoning"] },
  { name: "Zoya Ahmed", subjects: ["English", "Public Speaking"] },
  { name: "Om Prakash", subjects: ["History"] },
  { name: "Lavanya Rajan", subjects: ["Economics", "Geography"] },
  { name: "Aditi Bose", subjects: ["Science", "Physics"] },
  { name: "Kunal Oberoi", subjects: ["Robotics", "Artificial Intelligence"] },
  { name: "Shreya Ghosh", subjects: ["Grammar", "Literature", "English"] },
  { name: "Rehan Sheikh", subjects: ["Coding", "Web Development", "Python"] },
  { name: "Isha Kapoor", subjects: ["Drawing", "Art"] },
  { name: "Varun Prabhu", subjects: ["Chemistry", "Environmental Science"] },
  { name: "Gauri Apte", subjects: ["Mathematics", "Competitive Exams"] },
  { name: "Naveen Krishnan", subjects: ["Computer Science", "Programming"] },
  { name: "Pallavi Nayak", subjects: ["Biology", "Science"] },
  { name: "Farhan Ansari", subjects: ["Logical Reasoning", "Mathematics"] },
  { name: "Tara Bhatia", subjects: ["Music", "Public Speaking"] },
  { name: "Abhinav Suri", subjects: ["Physics", "Robotics"] },
  { name: "Radhika Iyengar", subjects: ["English", "Literature"] },
  { name: "Yuvraj Solanki", subjects: ["Geography", "History", "Economics"] },
  { name: "Charvi Mehra", subjects: ["Art", "Environmental Science"] },
  { name: "Ansh Bajaj", subjects: ["Web Development", "Artificial Intelligence"] },
  { name: "Diya Krishnamurthy", subjects: ["Chemistry", "Mathematics"] },
  { name: "Vihaan Kohli", subjects: ["Coding", "Computer Science", "Robotics"] },
  { name: "Myra Chandra", subjects: ["Spanish", "French"] },
  { name: "Reyansh Dutta", subjects: ["Competitive Exams", "Logical Reasoning", "Mathematics"] },
  { name: "Ahana Basu", subjects: ["Science", "Biology", "Chemistry"] },
];
